# Generated by Django 5.1.7 on 2025-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100, unique=True)),
                ('user_fullName', models.CharField(default='', max_length=60)),
                ('user_phoneNumber', models.CharField(default='', max_length=11)),
                ('user_description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
