# Generated by Django 5.1.7 on 2025-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='user_fullName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='users',
            name='user_phoneNumber',
            field=models.CharField(default='', max_length=11),
        ),
    ]
