# Generated by Django 5.1.7 on 2025-03-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_service', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
