# Generated by Django 5.1.7 on 2025-03-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_service', '0003_alter_favorite_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
